export type AdminRole = 'ADMIN' | 'SUPER_ADMIN'

export type AdminPermission =
  | 'DASHBOARD_READ'
  | 'CUSTOMERS_READ'
  | 'PRODUCTS_MANAGE'
  | 'RELEASES_MANAGE'
  | 'LICENSES_MANAGE'
  | 'PAYMENTS_READ'
  | 'TOKENS_READ'
  | 'LLM_POOL_READ'
  | 'MONITORING_READ'
  | 'SKILLS_MANAGE'
  | 'SUPPORT_MANAGE'
  | 'COMMUNITY_MANAGE'
  | 'SETTINGS_MANAGE'
  | 'ADMIN_USERS_MANAGE'

const SUPER_ADMIN_PERMISSIONS: AdminPermission[] = [
  'DASHBOARD_READ',
  'CUSTOMERS_READ',
  'PRODUCTS_MANAGE',
  'RELEASES_MANAGE',
  'LICENSES_MANAGE',
  'PAYMENTS_READ',
  'TOKENS_READ',
  'LLM_POOL_READ',
  'MONITORING_READ',
  'SKILLS_MANAGE',
  'SUPPORT_MANAGE',
  'COMMUNITY_MANAGE',
  'SETTINGS_MANAGE',
  'ADMIN_USERS_MANAGE',
]

const ADMIN_PERMISSIONS: AdminPermission[] = [
  'DASHBOARD_READ',
  'CUSTOMERS_READ',
  'PRODUCTS_MANAGE',
  'RELEASES_MANAGE',
  'LICENSES_MANAGE',
  'PAYMENTS_READ',
  'TOKENS_READ',
  'LLM_POOL_READ',
  'MONITORING_READ',
  'SKILLS_MANAGE',
  'SUPPORT_MANAGE',
  'COMMUNITY_MANAGE',
]

export const ADMIN_ROLE_PERMISSIONS: Record<AdminRole, AdminPermission[]> = {
  SUPER_ADMIN: SUPER_ADMIN_PERMISSIONS,
  ADMIN: ADMIN_PERMISSIONS,
}
